"""Shareable call report (HTML, printable). Built on demand from the immutable transcript and safety decisions.

Deliberately EXCLUDES the user's private notes and the assistant's suggestions: this file is meant to be shown to
family, a bank or the police. All transcript text is HTML-escaped (it is untrusted caller speech).
"""
from __future__ import annotations

import datetime as dt
from html import escape

from . import safety
from .session import Session

PATTERNS = [  # most specific first; mirrors the dashboard banner
    ("digital_arrest", "a fake “digital arrest” scam"), ("upi_pin", "a UPI “refund” scam"),
    ("remote_access", "a remote-access scam"), ("kyc_update", "a fake KYC / SIM-block scam"),
    ("parcel_scam", "a fake parcel / customs scam"), ("otp_or_code", "a bank OTP scam"),
    ("payment", "a money-transfer scam"), ("password", "a password-theft scam"),
]
CATEGORY = {
    "otp_or_code": "OTP / security code", "upi_pin": "UPI PIN", "password": "Password", "payment": "Money transfer",
    "remote_access": "Remote-access app", "kyc_update": "KYC / Aadhaar / PAN", "digital_arrest": "Fake police / CBI",
    "parcel_scam": "Parcel / customs", "pressure": "Pressure / threat", "other": "Sensitive request",
}


def _t(ms: int) -> str:
    s = ms // 1000
    return f"{s // 60:02d}:{s % 60:02d}"


def build(s: Session) -> tuple[str, str]:
    """Returns (filename, html)."""
    start = dt.datetime.fromtimestamp(s.started_at)
    danger = [a for a in s.assessments.values() if a.alert == "danger"]
    cats = {a.category for a in danger}
    pattern = next((p for c, p in PATTERNS if c in cats), "a common phone-scam pattern" if danger else None)
    utts = sorted(s.utterances.values(), key=lambda u: u.start_ms)

    if pattern:
        verdict = (f'<div class="verdict bad"><b>This call matched {escape(pattern)}.</b> '
                   f'{len(danger)} suspicious request{"s" if len(danger) != 1 else ""} were flagged.</div>')
    else:
        verdict = '<div class="verdict ok"><b>No suspicious requests were flagged on this call.</b></div>'

    flagged = "".join(
        f"<tr><td class=mono>{_t(a.evidence[0].start_ms) if a.evidence else ''}</td><td>{escape(CATEGORY.get(a.category, a.category))}</td>"
        f"<td>“{escape(a.evidence[0].text) if a.evidence else ''}”</td><td>{escape(safety.describe(a.intent, a.category)[1])}</td></tr>"
        for a in sorted(danger, key=lambda a: a.evidence[0].start_ms if a.evidence else 0))
    flagged_ids = {a.trigger_id for a in danger}
    transcript = "".join(
        f'<tr class="{"flag" if u.id in flagged_ids else ""}"><td class=mono>{_t(u.start_ms)}</td>'
        f'<td>{"You" if u.source == "HOST" else "Caller"}</td><td>{escape(u.text)}</td></tr>' for u in utts)
    approved = [t for t in s.tasks.values() if t.status == "approved"]
    tasks = "".join(f"<li>{escape(t.description)}{f' — <i>{escape(t.due_text)}</i>' if t.due_text else ''}</li>" for t in approved)

    duration = f" · {int((s.ended_at - s.started_at) // 60)} min {int((s.ended_at - s.started_at) % 60)} s" if s.ended_at else ""
    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Call report — {start:%d %b %Y %H:%M}</title>
<meta name="viewport" content="width=device-width, initial-scale=1"><style>
body{{font:14px/1.55 -apple-system,"Segoe UI",Arial,sans-serif;color:#111318;max-width:860px;margin:32px auto;padding:0 20px}}
h1{{font-size:24px;margin:0 0 4px}}h2{{font-size:16px;margin:28px 0 8px}}.dim{{color:#6b7280;font-size:12.5px}}
.verdict{{padding:12px 14px;border-radius:8px;margin:18px 0;border:1px solid}}.bad{{background:#fef2f2;border-color:#fecaca;color:#7f1d1d}}
.ok{{background:#ecfdf5;border-color:#a7f3d0;color:#065f46}}table{{width:100%;border-collapse:collapse}}
th,td{{text-align:left;padding:7px 9px;border-bottom:1px solid #e7e9ee;vertical-align:top}}th{{font-size:12px;color:#6b7280}}
tr.flag td{{background:#fef2f2}}.mono{{font-family:ui-monospace,Menlo,monospace;font-size:12px;white-space:nowrap}}
.box{{background:#f6f7f9;border-radius:8px;padding:12px 14px}}@media print{{body{{margin:0}}}}
</style></head><body>
<h1>Call report</h1>
<div class="dim">{start:%A, %d %B %Y, %H:%M}{duration} · generated by CallPilot on this device</div>
{verdict}
{"<h2>What to do</h2><div class=box>If you shared any code, PIN or money: call your bank immediately using the number on your card, and report the call on the national cyber-crime helpline <b>1930</b> or at <b>cybercrime.gov.in</b>. Keep this report.</div>" if pattern else ""}
{"<h2>Suspicious requests</h2><table><tr><th>Time</th><th>Type</th><th>Exact words</th><th>Advice</th></tr>" + flagged + "</table>" if danger else ""}
{"<h2>Summary</h2><p>" + escape(s.summary) + "</p>" if s.summary else ""}
{"<h2>Follow-ups you approved</h2><ul>" + tasks + "</ul>" if approved else ""}
<h2>Full transcript</h2>
<table><tr><th>Time</th><th>Who</th><th>What was said</th></tr>{transcript or "<tr><td colspan=3>No speech was transcribed.</td></tr>"}</table>
<p class="dim" style="margin-top:24px">“You” means audio from this device’s microphone; “Caller” means the other side of the call — not voice
identification. Speech-to-text and AI judgements can be wrong. Flags describe behaviour that matches known scam patterns; they are
not proof of fraud. Private notes and assistant suggestions are intentionally not included.</p>
</body></html>"""
    return f"callpilot-call-report-{start:%Y%m%d-%H%M}.html", html
